@echo off
REM zip.bat for minizip on Windows
REM required by `(emacs-home* "config/direds.el")'
REM generated by `(nore-emacs)'

REM local variable declaration

setlocal EnableDelayedExpansion

set _OPT=%%*
set _ZIP=
set _ARGV=

REM parsing command line arguments

:getopt
if "%%1"=="-mX0" set _OPT=%%_OPT:-mX0=-0%% & shift & goto :getopt

REM ignore options
if "%%1"=="-r" set _OPT=%%_OPT:-r=%% & shift & goto :getopt
if "%%1"=="--filesync" set _OPT=%%_OPT:--filesync=%% & shift & goto :getopt
if "%%1"=="-rmTq" set _OPT=%%_OPT:-rmTq=%% & shift & goto :getopt

REM extract zip and argv
if not "%%1"=="" (
  if "%%_ZIP%%"=="" (
    if "%%_ARGV%%"=="" (
      set _ZIP=%%1
    )
  ) else (
    set _ARGV=%%_ARGV%% %%1
  )
  set _OPT=!_OPT:%%1=!
  shift
  goto :getopt
)

REM minizip recursive call

call :loop %%_ARGV%%
goto :end

:zip
set _file=%%1
set _file=%%_file:./=%%
if not "%%_file%%"=="%%_ZIP%%" (
  if exist %%_ZIP%% (
    minizip %%_OPT%% -a %%_ZIP%% %%_file%%
  ) else (
    minizip %%_OPT%% %%_ZIP%% %%_file%%
  )
)
goto :end

:loop
for %%%%i in (%%*) do (
  if exist "%%%%i/*" (
    for %%%%f in (%%%%i/*) do (
      call :loop %%%%i/%%%%f
    )
    for /d %%%%d in (%%%%i/*) do (
      call :loop %%%%i/%%%%d
    )
  ) else (
    call :zip %%%%i
  )
)

:end
