@echo off
REM zip.bat for 7z on Windows
REM required by `(emacs-home* "config/direds.el")'
REM generated by `(nore-emacs)'

REM local variable declaration

setlocal EnableDelayedExpansion

set _OPT=%%*
set _ZIP=
set _ARGV=

REM parsing command line arguments

:getopt
if "%%1"=="-mX0" set _OPT=%%_OPT:-mX0=-mx0%% & shift & goto :getopt
if "%%1"=="-0" set _OPT=%%_OPT:-0=-mx0%% & shift & goto :getopt
if "%%1"=="-9" set _OPT=%%_OPT:-9=-mx9%% & shift & goto :getopt

REM ignore options
if "%%1"=="-r" set _OPT=%%_OPT:-r=%% & shift & goto :getopt
if "%%1"=="--filesync" set _OPT=%%_OPT:--filesync=%% & shift & goto :getopt
if "%%1"=="-rmTq" set _OPT=%%_OPT:-rmTq=%% & shift & goto :getopt

REM extract zip and argv
if not "%%1"=="" (
  if "%%_ZIP%%"=="" (
    if "%%_ARGV%%"=="" (
      set _ZIP=%%1
    )
  ) else (
    set _ARGV=%%_ARGV%% %%1
  )
  set _OPT=!_OPT:%%1=!
  shift
  goto :getopt
)

REM 7z call
7z a %%_OPT%% -tzip -- %%_ZIP%% %%_ARGV%%
if exist %%_ZIP%% (
  7z d %%_OPT%% -tzip -- %%_ZIP%% %%_ZIP%%
)
