;; -*- lexical-binding:t -*-
;;;;
;; Nore Emacs
;; https://github.com/junjiemars/.emacs.d
;;;;
;; docs.el
;;;;

(defmacro if-bin-gswin64/32c% (then &rest body)
  (declare (indent 1))
  `(if% (or (executable-find% "gswin64c")
            (executable-find% "gswin32c"))
       ,then
     (progn% ,@body)))

(defmacro unless-bin-gswin64/32c% (&rest body)
  (declare (indent 0))
  (if-bin-gswin64/32c%
      `(comment ,body)
    (when% (executable-find% "mutool")
      `(progn% ,@body))))

(defmacro when-bin-mudraw% (&rest body)
  (declare (indent 0))
  `(if% (and (executable-find% "mudraw")
             (executable-find% "pdfinfo"))
       (comment ,@body)
     (progn% ,@body)))

(unless-bin-gswin64/32c%
  (defun make-mudraw-bat (mutool)
    "Make mudraw.bat in \\=`exec-path\\=' for mutool.exe ."
    (write-file*
     (concat "@echo off\n"
             (format "REM mudraw.bat for %s on Windows\n" mutool)
             "REM generated by Nore Emacs " (nore-emacs) "\n\n"
             "setlocal EnableDelayedExpansion\n\n"
             "mutool draw %*\n")
     (v-home% ".exec/mudraw.bat"))))

(unless-bin-gswin64/32c%
  (defun make-pdfinfo-bat (mutool)
    "Make pdfinfo.bat in \\=`exec-path\\=' for mutool.exe ."
    (write-file*
     (concat "@echo off\n"
             (format "REM pdfinfo.bat for %s on Windows\n" mutool)
             "REM generated by Nore Emacs " (nore-emacs) "\n\n"
             "setlocal EnableDelayedExpansion\n\n"
             "mutool info %*\n")
     (v-home% ".exec/pdfinfo.bat"))))

(when-bin-mudraw%
  ;; fix: the builtin `doc-view-mode-p' does not support mupdf.
  (defun doc-view-mode-p* (type)
    (let ((r (apply '_doc-view-mode-p_ type)))
      (cond ((eq 'pdf type) t)
            (t r)))))

(defun on-doc-view-init! ()
  "On \\=`doc-view\\=' initialization."
  (if-bin-gswin64/32c%
      (setq% doc-view-ghostscript-program
             (or (executable-find% "gswin32c")
                 (executable-find% "gswin64c"))
             doc-view)
    ;; unless gswin64c/gswin32c
    (when% (executable-find% "mutool")
      (unless (executable-find% "mudraw")
        (make-mudraw-bat (executable-find% "mutool")))
      (unless (executable-find% "pdfinfo")
        (make-pdfinfo-bat (executable-find% "mutool")))
      (when-bin-mudraw%
        (defadvice* '_doc-view-mode-p_
          'doc-view-mode-p #'doc-view-mode-p*)))))



(provide 'docs)

;; end of docs.el
