;;;; -*- lexical-binding:t -*-
;;;;
;; Nore Emacs
;; https://github.com/junjiemars/.emacs.d
;;;;
;; on-docview-autoload.el
;;;;


(if% (or (executable-find% "gswin64c")
         (executable-find% "gswin32c"))

    (with-eval-after-load 'doc-view
      (setq% doc-view-ghostscript-program
             (or (executable-find% (format "gswin%dc" (cdr (platform-arch))))
                 (executable-find% "gswin32c")
                 (executable-find% "gswin64c"))
             'doc-view))

  (when% (executable-find% "mutool")
    (eval-when-compile

      (defun make-mudraw-bat (mutool)
        "Make mudraw.bat in \\=`exec-path\\=' for mutool.exe ."
        (save-str-to-file
         (concat "@echo off\n"
                 (format "REM mudraw.bat for %s on Windows\n" mutool)
                 "REM generated by Nore Emacs " (nore-emacs) "\n\n"
                 "setlocal EnableDelayedExpansion\n\n"
                 "mutool draw %*\n")
         (v-home% ".exec/mudraw.bat")))

      (defun make-pdfinfo-bat (mutool)
        "Make pdfinfo.bat in \\=`exec-path\\=' for mutool.exe ."
        (save-str-to-file
         (concat "@echo off\n"
                 (format "REM pdfinfo.bat for %s on Windows\n" mutool)
                 "REM generated by Nore Emacs " (nore-emacs) "\n\n"
                 "setlocal EnableDelayedExpansion\n\n"
                 "mutool info %*\n")
         (v-home% ".exec/pdfinfo.bat")))


      (unless (executable-find% "mudraw")
        (make-mudraw-bat (executable-find% "mutool")))

      (unless (executable-find% "pdfinfo")
        (make-pdfinfo-bat (executable-find% "mutool"))))


    (when% (and (executable-find% "mudraw")
                (executable-find% "pdfinfo"))

      (defadvice doc-view-mode-p (after doc-view-mode-p-after disable)
        "fix: the builtin \\=`doc-view-mode-p\\=' does not support mupdf."
        (when (eq 'pdf (ad-get-arg 0))
          (setq ad-return-value t)))

      (with-eval-after-load 'doc-view
        (ad-enable-advice #'doc-view-mode-p 'after
                          "doc-view-mode-p-after")
        (ad-activate #'doc-view-mode-p t)))))


;; end of on-docview-autoload.el
