name: More Reasonable Emacs

on:
  pull_request:
    branches:
      - cc
  push:
    branches:
      - cc

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # checkout history and tags

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install emacs
      - name: Test
        run: |
          _TEST_=bone ./test.sh
          _TEST_=axiom ./test.sh
          _TEST_=package ./test.sh

  MacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # checkout history and tags
      - name: Install Dependencies
        run: |
          brew install emacs
      - name: Test
        run: |
          _TEST_=bone ./test.sh
          _TEST_=axiom ./test.sh
          _TEST_=package ./test.sh

  Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # checkout history and tags

    - name: Install Dependencies
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: git emacs
    - name: Test
      run: |
        _TEST_=bone ./test.sh
        _TEST_=axiom ./test.sh
        _TEST_=package ./test.sh

  Matrix:
    runs-on: ${{ matrix.os }}
    matrix:
      os: [ubuntu-latest]
      emacs_version:
        - 24.5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # checkout history and tags
      - name: Test
        run: |
          _TEST_=axiom ./test.sh

# eof
