name: Nore Emacs

on:
  pull_request:
    branches:
      - cc
  push:
    branches:
      - cc

jobs:

  Test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies (Linux)
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt-get update
          sudo apt-get install emacs
      - name: Install Dependencies (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install emacs
      - name: Install Dependencies (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            mingw-w64-x86_64-gcc
            emacs
          echo "_shell_='msys {0}'" >> $GITHUB_ENV
      - name: Test (${{ matrix.os }})
        shell: ${{ env._shell_ }}
        run: |
          _TEST_=bone ./test.sh
          _TEST_=axiom ./test.sh
          _TEST_=package ./test.sh

  # Emacs:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       emacs: [
  #       emacs-27,
  #       emacs-26,
  #       emacs-25,
  #       emacs-24,
  #       emacs-23,
  #       emacs-22
  #       ]
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1 # without checkout history and tags
  #     - name: Install Dependencies
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install build-essential gcc-multilib
  #         sudo apt-get install gnutls-bin pciutils texinfo
  #     - name: Build Emacs
  #       env:
  #         emacs_source: "https://github.com/emacs-mirror/emacs.git"
  #       run: |
  #         if [ "${{matrix.emacs}}" = "emacs-22" ]; then
  #           git clone --depth=1 --branch="old-branches/EMACS_22_BASE" ${{env.emacs_source}} ${{matrix.emacs}}
  #         else
  #           git clone --depth=1 --branch=${{matrix.emacs}} ${{env.emacs_source}} ${{matrix.emacs}}
  #         fi
  #         cd ${{matrix.emacs}}
  #         if [ "${{matrix.emacs}}" = "emacs-27" ]; then
  #           ./autogen.sh
  #           ./configure --with-x-toolkit=no --with-xpm=ifavailable --with-gif=ifavailable --with-gnutls=ifavailable
  #           sudo make -j4 install
  #         elif [ "${{matrix.emacs}}" = "emacs-26" ]; then
  #           autoreconf -i
  #           ./configure --with-x-toolkit=no --with-xpm=no --with-gif=no --with-gnutls=no
  #           sudo make -j4 install
  #         elif [ "${{matrix.emacs}}" = "emacs-25" ]; then
  #           ./autogen.sh
  #           ./configure --with-x-toolkit=no --with-xpm=no --with-gif=no --with-gnutls=no
  #           sudo make -j4 install
  #         elif [ "${{matrix.emacs}}" = "emacs-24" ]; then
  #           ./autogen.sh
  #           ./configure --with-x-toolkit=no --with-xpm=no --with-gif=no --with-gnutls=no
  #           sudo make -j4 install
  #         elif [ "${{matrix.emacs}}" = "emacs-23" ]; then
  #           ./configure --with-x-toolkit=no --with-crt-dir=/usr/lib/`uname -m`-linux-gnu --with-xpm=no --with-jpeg=no --with-gif=no --without-makeinfo
  #           sudo make -j4 install
  #         elif [ "${{matrix.emacs}}" = "emacs-22" ]; then
  #           ./configure --with-x-toolkit=no --with-xpm=no --with-jpeg=no --with-gif=no --without-makeinfo
  #           sudo make -j4 install
  #         fi
  #     - name: Test
  #       run: |
  #         _TEST_=bone ./test.sh
  #         _TEST_=axiom ./test.sh
  #         _TEST_=package ./test.sh

# eof
