name: More Reasonable Emacs

on:
  pull_request:
    branches:
      - cc
  push:
    branches:
      - cc

jobs:
  # Linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1 # without checkout history and tags
  #     - name: Install Dependencies
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install emacs
  #     - name: Test
  #       run: |
  #         _TEST_=bone ./test.sh
  #         _TEST_=axiom ./test.sh
  #         _TEST_=package ./test.sh

  # MacOS:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1 # without checkout history and tags
  #     - name: Install Dependencies
  #       run: |
  #         brew install emacs
  #     - name: Test
  #       run: |
  #         _TEST_=bone ./test.sh
  #         _TEST_=axiom ./test.sh
  #         _TEST_=package ./test.sh

  # Windows:
  #   runs-on: windows-latest
  #   defaults:
  #     run:
  #       shell: msys2 {0}

  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       fetch-depth: 1 # without checkout history and tags

  #   - name: Install Dependencies
  #     uses: msys2/setup-msys2@v2
  #     with:
  #       update: true
  #       install: git emacs
  #   - name: Test
  #     run: |
  #       _TEST_=bone ./test.sh
  #       _TEST_=axiom ./test.sh
  #       _TEST_=package ./test.sh

  Matrix-Linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        emacs:
          # - 22.3
          # - 23.4
          # - 24.5
          # - 25.3
          - 26.3
          - 27.1
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1 # checkout history and tags
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install build-essential
      - name: Build Emacs
        run: |
          git clone --depth=1 --branch=emacs-${{matrix.emacs}} https://github.com/emacs-mirror/emacs.git emacs-${{matrix.emacs}}
          cd emacs-${{matrix.emacs}}
          autoreconf -i
          ./configure --without-all
          sudo make install
      - name: Test
        run: |
          _TEST_=axiom _EMACS_=emacs-${{matrix.emacs}} ./test.sh

# eof
