name: Nore Emacs

on:
  pull_request:
    branches:
      - cc
  push:
    branches:
      - cc

jobs:

  # Ubuntu:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-20.04, ubuntu-18.04]
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1 # without checkout history and tags
  #     - name: Install Dependencies
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install emacs
  #     - name: Test
  #       run: |
  #         _TEST_=bone ./test.sh
  #         _TEST_=axiom ./test.sh
  #         _TEST_=package ./test.sh
  
  Matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs: [emacs-27, emacs-26, emacs-25, emacs-23]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1 # without checkout history and tags
      - name: Install Dependencies
        env:
          emacs_source: "https://github.com/emacs-mirror/emacs.git"
        run: |
          sudo apt-get update
          sudo apt-get install build-essential gcc-multilib
          git clone --depth=1 --branch=${{matrix.emacs}} ${{env.emacs_source}} ${{matrix.emacs}}
          ls -lh .
          cd ${{matrix.emacs}}
          ls -lh .
          ./configure
          make -j4 install
      - name: Test
        run: |
          _TEST_=bone ./test.sh
          _TEST_=axiom ./test.sh
          _TEST_=package ./test.sh


  # MacOS:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1 # without checkout history and tags
  #     - name: Install Dependencies
  #       run: |
  #         brew install emacs
  #     - name: Test
  #       run: |
  #         _TEST_=bone ./test.sh
  #         _TEST_=axiom ./test.sh
  #         _TEST_=package ./test.sh


  # Windows:
  #   runs-on: windows-latest
  #   defaults:
  #     run:
  #       shell: msys2 {0}
  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       fetch-depth: 1 # without checkout history and tags
  #   - name: Install Dependencies
  #     uses: msys2/setup-msys2@v2
  #     with:
  #       update: true
  #       install: >-
  #         make
  #         mingw-w64-x86_64-gcc
  #         emacs
  #   - name: Test
  #     run: |
  #       _TEST_=bone ./test.sh
  #       _TEST_=axiom ./test.sh
  #       _TEST_=package ./test.sh

  # Matrix-Linux:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       emacs:
  #         - emacs-27.1
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1 # checkout history and tags
  #     # - name: Install Dependencies
  #     #   run: |
  #     #     sudo apt update
  #     #     sudo apt install build-essential
  #     - name: Build Emacs
  #       run: |
  #         git config --global gc.auto 0
  #         git config --global advice.detachedHead false
  #         git clone --depth=1 --branch=${{matrix.emacs}} --no-tags https://github.com/emacs-mirror/emacs.git ${{matrix.emacs}}
  #         cd ${{matrix.emacs}}
  #         autoreconf -i
  #         ./configure --program-transform-name=${{matrix.emacs}} --without-all --with-x-toolkit=no
  #         sudo make -j4 install
  #     - name: Test
  #       run: |
  #         _TEST_=axiom _EMACS_=${{matrix.emacs}} ./test.sh

# eof
